export default [
  {
    path: '/user',
    layout: false,
    routes: [
      {
        path: '/user',
        routes: [
          {
            name: 'login',
            path: '/user/login',
            access: 'loggedOut',
            component: './User/login',
          },
          {
            name: 'reset',
            path: '/user/reset-password',
            access: 'loggedOut',
            component: './User/reset',
          },
        ],
      },
    ],
  },
  {
    name: 'Dashboard',
    icon: 'dashboard',
    path: '/reports',
    access: 'reportListPermission',
    component: './Reports',
  },
  {
    path: '/courses',
    name: 'Courses',
    icon: 'fire',
    access: 'coursesPermission',
    routes: [
      {
        path: '/courses',
        redirect: '/courses/list',
        access: 'coursesPermission',
      },
      {
        path: '/courses/:courseTab',
        icon: 'fire',
        access: 'courseListPermission',
        component: './Courses',
        hideInMenu: true,
      },
      {
        path: '/courses/list',
        name: 'List',
        icon: 'fire',
        access: 'courseListPermission',
        component: './Courses',
      },
      {
        path: '/courses/list/:course',
        name: 'Form',
        icon: 'book',
        access: 'courseDetailsPermission',
        component: './Courses/form',
        hideInMenu: true,
      },
      {
        path: '/courses/list/:course/:tab',
        name: 'Course Form',
        icon: 'book',
        access: 'courseDetailsPermission',
        component: './Courses/form',
        hideInMenu: true,
        exact: false,
      },
      {
        path: '/courses/scorms',
        name: 'SCORMs',
        icon: 'experiment',
        access: 'scormListPermission',
        component: './Scorm',
      },
      {
        path: '/courses/scorms/preview/:uuid',
        name: 'SCORMs',
        icon: 'experiment',
        access: 'scormDetailsPermission',
        component: './Scorm/preview',
        hideInMenu: true,
      },
      {
        path: '/courses/categories',
        name: 'Categories',
        icon: 'calculator',
        access: 'categoryListPermission',
        component: './Categories',
      },
      {
        path: '/courses/access',
        name: 'Acces aux cours',
        icon: 'experiment',
        access: 'courseAccessListPermission',
        component: './CourseAccess',
      },
      {
        path: '/courses/quiz-reports',
        name: 'Quiz Reports',
        icon: 'read',
        access: 'coursesQuizReportsListPermission',
        component: './QuizReports',
      },
      {
        path: '/courses/quiz-reports/:reportId',
        hideInMenu: true,
        name: 'Details',
        icon: 'read',
        access: 'coursesQuizReportsListPermission',
        component: './QuizReports/details',
      },
    ],
  },
  {
    path: '/sales',
    name: 'Sales',
    access: 'salesPermission',
    icon: 'shopping',
    routes: [
      {
        path: '/sales',
        redirect: '/sales/orders',
        access: 'salesPermission',
      },
      {
        path: '/sales/orders',
        name: 'Orders',
        icon: 'fund',
        access: 'orderListPermission',
        component: './Orders',
      },
      {
        path: '/sales/payments',
        name: 'Payments',
        icon: 'dollar',
        access: 'paymentListPermission',
        component: './Payments',
      },
      {
        path: '/sales/products',
        name: 'Products',
        icon: 'shopping-cart',
        access: 'productsListPermission',
        component: './Products',
      },
      {
        path: '/sales/products/:id',
        access: 'productsDetailsPermission',
        component: './Products/form',
        hideInMenu: true,
      },
      {
        path: '/sales/products/:id/:tab',
        access: 'productsDetailsPermission',
        component: './Products/form',
        hideInMenu: true,
      },
    ],
  },
  {
    path: '/users',
    name: 'Users',
    access: 'usersPermission',
    icon: 'user',
    routes: [
      {
        path: '/users',
        redirect: '/users/list',
        access: 'usersPermission',
      },
      {
        path: '/users/list',
        name: 'List',
        icon: 'user',
        access: 'userListPermission',
        component: './Users',
      },
      {
        path: '/users/list/new',
        icon: 'user',
        component: './Users/User',
        access: 'userCreatePermission',
        hideInMenu: true,
      },
      {
        name: 'Roles',
        path: '/users/roles',
        icon: 'lock',
        access: 'roleListPermission',
        component: './Roles',
      },
      {
        name: 'Permissions',
        path: '/users/roles/:name',
        icon: 'lock',
        access: 'roleDetailsPermission',
        component: './Roles/form',
        hideInMenu: true,
      },
      {
        path: '/users/:user/:tab',
        icon: 'user',
        access: 'userDetailsPermission',
        component: './Users/User',
        hideInMenu: true,
      },
      {
        path: '/users/fields',
        icon: 'user',
        access: 'userDetailsPermission',
        component: './Users/fields',
        hideInMenu: true,
      },
      {
        name: 'Notifications',
        path: '/users/notifications',
        access: 'UserBulkNotificationListPermission',
        component: './Users/BulkNotifications',
      },
      {
        name: 'Notifications',
        path: '/users/notifications/:template',
        access: 'UserBulkNotificationListPermission',
        component: './Users/BulkNotifications',
        hideInMenu: true,
      },
      {
        path: '/users/notifications/:template/:id',
        name: 'Notifications',
        access: 'UserBulkNotificationCreatePermission',
        component: './Users/BulkNotifications/form',
        hideInMenu: true,
      },
    ],
  },
  {
    path: '/my-profile',
    name: 'My Profile',
    access: 'userProfilePermission',
    hideInMenu: true,
    routes: [
      {
        path: '/my-profile',
        redirect: '/my-profile/general',
        access: 'userProfilePermission',
      },
      {
        path: '/my-profile/:tab',
        name: 'My Profile',
        access: 'userProfilePermission',
        component: './Users/myProfile',
        hideInMenu: true,
      },
    ],
  },
  {
    path: '/teacher',
    name: 'Teacher',
    access: 'teacherPermission',
    icon: 'experiment',
    routes: [
      {
        path: '/teacher',
        redirect: '/teacher/subjects',
        access: 'teacherPermission',
      },
      {
        path: '/teacher/subjects',
        name: 'Subjects',
        icon: 'book',
        access: 'teacherSubjectListPermission',
        component: './TeacherSubjects',
      },
      {
        path: '/teacher/subjects/:subjectId',
        name: 'Form',
        icon: 'book',
        access: 'teacherSubjectDetailsPermission',
        component: './TeacherSubjects/form',
        hideInMenu: true,
      },
      {
        path: '/teacher/subjects/:subjectId/:tab',
        name: 'Subject Form',
        icon: 'book',
        access: 'teacherSubjectDetailsPermission',
        component: './TeacherSubjects/form',
        hideInMenu: true,
      },
    ],
  },
  {
    path: '/competency-challenges',
    name: 'Competency challenges',
    access: 'competencyChallengesPermission',
    icon: 'trophy',
    routes: [
      {
        path: '/competency-challenges',
        redirect: '/competency-challenges/list',
        access: 'competencyChallengesPermission',
      },
      {
        path: '/competency-challenges/list',
        name: 'List',
        access: 'competencyChallengesListPermission',
        component: './CompetencyChallenges',
      },
      {
        path: '/competency-challenges/:id/:tab',
        name: 'Competency challenge',
        access: 'competencyChallengesFormPermission',
        component: './CompetencyChallenges/form',
        hideInMenu: true,
      },
    ],
  },
  {
    name: 'Analytics',
    path: '/analytics',
    access: 'analyticsPermission',
    icon: 'rise',
    routes: [
      {
        path: '/analytics',
        redirect: '/analytics/notifications',
        access: 'analyticsPermission',
      },
      {
        name: 'Notifications',
        icon: 'alert',
        path: '/analytics/notifications',
        access: 'notificationListPermission',
        component: './Notifications',
      },
      {
        name: 'reports',
        icon: 'project',
        path: '/analytics/reports',
        access: 'reportListPermission',
        component: './Reports',
      },
      {
        name: 'Logs',
        icon: 'history',
        path: '/analytics/logs',
        access: 'trackerListPermission',
        component: './Logs',
      },
    ],
  },
  {
    name: 'Configuration',
    path: '/configuration',
    access: 'configurationPermission',
    icon: 'setting',
    routes: [
      {
        path: '/configuration',
        redirect: '/configuration/files',
        access: 'configurationPermission',
      },
      {
        path: '/configuration/files',
        name: 'Files',
        icon: 'folderOpen',
        access: 'fileListPermission',
        component: './Files',
      },
      {
        path: '/configuration/settings',
        name: 'settings',
        icon: 'calculator',
        access: 'settingListPermission',
        component: './Settings',
      },
      {
        path: '/configuration/settings/:tab',
        name: 'settings',
        icon: 'calculator',
        access: 'settingListPermission',
        component: './Settings',
        hideInMenu: true,
      },
      {
        path: '/configuration/templates',
        name: 'Templates',
        icon: 'highlight',
        access: 'templateDetailsPermission',
        component: './Templates',
      },
      {
        path: '/configuration/templates/:template',
        name: 'Templates',
        icon: 'highlight',
        access: 'templateDetailsPermission',
        component: './Templates',
        hideInMenu: true,
      },
      {
        path: '/configuration/templates/:template/:id',
        name: 'Templates',
        icon: 'highlight',
        access: 'templateDetailsPermission',
        component: './Templates/form',
        hideInMenu: true,
      },
    ],
  },
  {
    name: 'Other activities',
    path: '/other',
    access: 'otherPermission',
    icon: 'appstore',
    routes: [
      {
        path: '/other/consultation-access',
        name: 'Consultation Requests',
        icon: 'experiment',
        access: 'consultationAccessListPermission',
        component: './ConsultationsAccess',
      },
      {
        path: '/other/questionnaire',
        name: 'Questionnaire',
        icon: 'question',
        access: 'questionnaireListPermission',
        component: './Questionnaire',
      },
      {
        path: '/other/questionnaire/:questionnaireId',
        name: 'Questionnaire Form',
        access: 'questionnaireDetailPermission',
        component: './Questionnaire/form',
        hideInMenu: true,
      },
    ],
  },
  {
    access: 'reportListPermission',
    path: '/',
    redirect: '/reports',
  },
  {
    component: './404',
  },
];
